cpus        :  1
mem         : 512.0
uris        :
    - "file:///root/.dockercfg"
env:
  -
    name : AWS_DEFAULT_REGION
    value : "us-west-1"
container :
    type : DOCKER
    image : null
    net : host
    privileged : true
