# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mousera_jobs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mousera_jobs.proto',
  package='',
  serialized_pb=_b('\n\x12mousera_jobs.proto\"@\n\x03Job\x12\x17\n\x04type\x18\x01 \x02(\x0e\x32\t.Job.Type\"\x16\n\x04Type\x12\x0e\n\nCageReport\x10\x01*\x08\x08\x64\x10\x80\x80\x80\x80\x02\"\xd2\x01\n\nCageReport\x12\x0f\n\x07\x63\x61ge_id\x18\x01 \x01(\x05\x12\x16\n\x0ereport_targets\x18\x02 \x01(\t\x12\x12\n\nuser_email\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\x12\x12\n\naggregator\x18\x06 \x01(\t\x12\x15\n\rsampling_unit\x18\x07 \x01(\t\x12\x16\n\x0esampling_value\x18\x08 \x01(\t2\x1e\n\x03job\x12\x04.Job\x18\x64 \x01(\x0b\x32\x0b.CageReport')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_JOB_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Job.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CageReport', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=54,
  serialized_end=76,
)
_sym_db.RegisterEnumDescriptor(_JOB_TYPE)


_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Job.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOB_TYPE,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=86,
)


_CAGEREPORT = _descriptor.Descriptor(
  name='CageReport',
  full_name='CageReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cage_id', full_name='CageReport.cage_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='report_targets', full_name='CageReport.report_targets', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_email', full_name='CageReport.user_email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='CageReport.start_time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='CageReport.end_time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggregator', full_name='CageReport.aggregator', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sampling_unit', full_name='CageReport.sampling_unit', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sampling_value', full_name='CageReport.sampling_value', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='job', full_name='CageReport.job', index=0,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=299,
)

_JOB.fields_by_name['type'].enum_type = _JOB_TYPE
_JOB_TYPE.containing_type = _JOB
DESCRIPTOR.message_types_by_name['Job'] = _JOB
DESCRIPTOR.message_types_by_name['CageReport'] = _CAGEREPORT

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), dict(
  DESCRIPTOR = _JOB,
  __module__ = 'mousera_jobs_pb2'
  # @@protoc_insertion_point(class_scope:Job)
  ))
_sym_db.RegisterMessage(Job)

CageReport = _reflection.GeneratedProtocolMessageType('CageReport', (_message.Message,), dict(
  DESCRIPTOR = _CAGEREPORT,
  __module__ = 'mousera_jobs_pb2'
  # @@protoc_insertion_point(class_scope:CageReport)
  ))
_sym_db.RegisterMessage(CageReport)

_CAGEREPORT.extensions_by_name['job'].message_type = _CAGEREPORT
Job.RegisterExtension(_CAGEREPORT.extensions_by_name['job'])

# @@protoc_insertion_point(module_scope)
